# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        ('accounting', '0002_auto_20180218_1904'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhasalert',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Alert'),
        ),
        migrations.AddField(
            model_name='customerhasalert',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.File'),
        ),
        migrations.AddField(
            model_name='contract',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit',
            name='contracts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Contract'),
        ),
        migrations.AddField(
            model_name='audit',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer'),
        ),
        migrations.AddField(
            model_name='audit',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Folder'),
        ),
        migrations.AddField(
            model_name='audit',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
