# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 04:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_busines_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_auto_20181105_2255'),
        ('services', '0003_auto_20181101_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApportionedAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyein', models.CharField(max_length=100)),
                ('unitnumb', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=100, null=True)),
                ('irpacount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApportionedAplicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AuditAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usdotpin', models.CharField(blank=True, max_length=100, null=True)),
                ('usdotnumb', models.CharField(blank=True, max_length=100, null=True)),
                ('drivernumb', models.CharField(blank=True, max_length=100, null=True)),
                ('unitnumb', models.CharField(blank=True, max_length=100, null=True)),
                ('auditormane', models.CharField(blank=True, max_length=100, null=True)),
                ('auditaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditAplicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('usdot', models.CharField(blank=True, max_length=20, null=True)),
                ('mc', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv', models.CharField(blank=True, max_length=20, null=True)),
                ('dateaplic', models.DateTimeField(default='2018-11-05 22:55')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flatbead', models.BooleanField(default=False)),
                ('van', models.BooleanField(default=False)),
                ('refer', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('otherdescrp', models.CharField(blank=True, max_length=100, null=True)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchAplicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_numb', models.CharField(blank=True, max_length=45, null=True)),
                ('experience', models.CharField(blank=True, max_length=5, null=True)),
                ('dob', models.CharField(blank=True, max_length=45, null=True)),
                ('lic_date_exp', models.DateField(blank=True, null=True)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAplicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FilesAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
                ('flies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.File')),
            ],
        ),
        migrations.CreateModel(
            name='IftaAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namebank', models.CharField(max_length=100)),
                ('rootingnumb', models.CharField(max_length=100)),
                ('accountnumb', models.CharField(max_length=100)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
            ],
        ),
        migrations.CreateModel(
            name='IftaAplicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
                ('licdriver', models.CharField(max_length=25)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
            ],
        ),
        migrations.CreateModel(
            name='NewCompanyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namecard', models.CharField(max_length=100)),
                ('credicard', models.CharField(max_length=16)),
                ('securitycode', models.CharField(max_length=5)),
                ('expdate', models.CharField(max_length=5)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('update', models.DateTimeField(default='2018-11-05 22:55')),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
                ('servicesaplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicesAplic')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAplic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('marke', models.CharField(blank=True, max_length=45, null=True)),
                ('vin', models.CharField(blank=True, max_length=20, null=True)),
                ('owned', models.BooleanField(default=False)),
                ('leased', models.BooleanField(default=False)),
                ('customeraplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAplicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dispatchload',
            name='prefix',
            field=models.CharField(default='invl', max_length=4),
        ),
        migrations.AlterField(
            model_name='dispatchload',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='auditaplic',
            name='customeraplic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic'),
        ),
        migrations.AddField(
            model_name='apportionedaplic',
            name='customeraplic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerAplic'),
        ),
    ]
