# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_busines_email'),
        ('services', '0004_auto_20181105_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApportionedAplicForm',
        ),
        migrations.DeleteModel(
            name='AuditAplicForm',
        ),
        migrations.DeleteModel(
            name='DispatchAplicForm',
        ),
        migrations.DeleteModel(
            name='DriverAplicForm',
        ),
        migrations.DeleteModel(
            name='IftaAplicForm',
        ),
        migrations.DeleteModel(
            name='NewCompanyForm',
        ),
        migrations.DeleteModel(
            name='VehicleAplicForm',
        ),
        migrations.AddField(
            model_name='customeraplic',
            name='folders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Folder'),
        ),
        migrations.AddField(
            model_name='iftaaplic',
            name='rtcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeraplic',
            name='dateaplic',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dispatchload',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processaplic',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
