# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20181110_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraplic',
            name='dateaplic',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='processaplic',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
