# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20181110_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraplic',
            name='dateaplic',
            field=models.DateTimeField(default='2018-11-11 20:08'),
        ),
        migrations.AlterField(
            model_name='dispatchload',
            name='start_date',
            field=models.DateField(default='2018-11-11'),
        ),
        migrations.AlterField(
            model_name='processaplic',
            name='update',
            field=models.DateTimeField(default='2018-11-11 20:08'),
        ),
    ]
