# Generated by Django 5.0 on 2023-12-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20181111_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='id_apl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='id_aud',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='id_con',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customerhasalert',
            old_name='id_cal',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dispatchload',
            old_name='id_inv',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='id_drv',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='id_tru',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ifta',
            old_name='id_ift',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='id_ins',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='id_com',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='customeraplic',
            name='dateaplic',
            field=models.DateTimeField(default='2023-12-08 03:56'),
        ),
        migrations.AlterField(
            model_name='dispatchload',
            name='start_date',
            field=models.DateField(default='2023-12-08'),
        ),
        migrations.AlterField(
            model_name='processaplic',
            name='update',
            field=models.DateTimeField(default='2023-12-08 03:56'),
        ),
    ]
