# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_busines_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='busines',
            name='color',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
