# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_auto_20180218_1904'),
        ('logistic', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckslogt',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Busines'),
        ),
        migrations.AddField(
            model_name='truckslogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.DriversLogt'),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionslogt',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Busines'),
        ),
        migrations.AddField(
            model_name='permissionslogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthasload',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load'),
        ),
        migrations.AddField(
            model_name='paymenthasload',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Payment'),
        ),
        migrations.AddField(
            model_name='loadshasfee',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Fee'),
        ),
        migrations.AddField(
            model_name='loadshasfee',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load'),
        ),
        migrations.AddField(
            model_name='load',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.DispatchLogt'),
        ),
        migrations.AddField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.DriversLogt'),
        ),
        migrations.AddField(
            model_name='load',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceshasload',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoice'),
        ),
        migrations.AddField(
            model_name='invoiceshasload',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load'),
        ),
        migrations.AddField(
            model_name='insurancelogt',
            name='accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='insurancelogt',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Busines'),
        ),
        migrations.AddField(
            model_name='insurancelogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.DriversLogt'),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='trucks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.TrucksLogt'),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverslogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivershaspayment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.DriversLogt'),
        ),
        migrations.AddField(
            model_name='drivershaspayment',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Payment'),
        ),
        migrations.AddField(
            model_name='dispatchlogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchloadhasload',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.DispatchLoad'),
        ),
        migrations.AddField(
            model_name='dispatchloadhasload',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load'),
        ),
        migrations.AddField(
            model_name='dispatchhaspayment',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.DispatchLogt'),
        ),
        migrations.AddField(
            model_name='dispatchhaspayment',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Payment'),
        ),
        migrations.AddField(
            model_name='diesel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.DriversLogt'),
        ),
        migrations.AddField(
            model_name='diesel',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerhasload',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer'),
        ),
        migrations.AddField(
            model_name='customerhasload',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Driver'),
        ),
        migrations.AddField(
            model_name='customerhasload',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load'),
        ),
        migrations.AddField(
            model_name='businesshasload',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Busines'),
        ),
        migrations.AddField(
            model_name='businesshasload',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load'),
        ),
    ]
