# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20180218_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverslogt',
            name='phone',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
