# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_driverslogt_phone'),
    ]

    operations = [

    ]
