# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_auto_20181105_2255'),
    ]

    operations = [

    ]
