# Generated by Django 5.0 on 2023-12-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_auto_20181111_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DispatchLoadHasLoad',
            new_name='DispatchLogtHasLoad',
        ),
        migrations.RenameField(
            model_name='businesshasload',
            old_name='id_bsl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customerhasload',
            old_name='id_csl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='diesel',
            old_name='id_dse',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dispatchhaspayment',
            old_name='id_pym',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dispatchlogt',
            old_name='id_dsp',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dispatchlogthasload',
            old_name='id_inl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='drivershaspayment',
            old_name='id_pym',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='driverslogt',
            old_name='id_dr',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='iftalogt',
            old_name='id_ift',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='insurancelogt',
            old_name='id_inr',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='invoiceshasload',
            old_name='id_inl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='id_lod',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='loadshasfee',
            old_name='id_lfe',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='paymenthasload',
            old_name='id_pyl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='permissionslogt',
            old_name='id_prm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='travelexpense',
            old_name='id_tre',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='truckslogt',
            old_name='id_tuk',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='dispatchlogt',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='dispatchlogt',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='dispatchlogthasload',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.dispatchlogt'),
        ),
    ]
