# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_busines_email'),
        ('accounting', '0003_auto_20181101_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business',
        ),
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ManyToManyField(to='tools.Busines'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, default='2018-11-04', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(default='2018-11-04'),
        ),
    ]
