# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20181104_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(),
        ),
    ]
