# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20181105_2255'),
    ]

    operations = [

    ]
