# Generated by Django 5.0 on 2023-12-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20190228_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id_acn',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='accountdescrip',
            old_name='id_acd',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id_cut',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id_emp',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employeehaspayment',
            old_name='id_pym',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='id_fee',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='comission_fee',
            new_name='commission_fee',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='id_inv',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='invoiceshasitem',
            old_name='id_ind',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id_sal',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='id_rec',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, default='2023-12-08', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(default='2023-12-08'),
        ),
    ]
